//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePurchase
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string NumProduct { get; set; }
        public string NumPurchase { get; set; }
        public string SaleProduct { get; set; }
    }
}
